apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cctv
  labels:
    ostraining: "lamp"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: php
      namespace: cctv
  template:
    metadata:
      labels:
        app: php
        namespace: cctv
    spec:
      containers:
      - name: php
        image: abhijith99954/cctv-php:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
             secretKeyRef:
                name: mysql-credentials
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom: 
             secretKeyRef:
                name: mysql-credentials
                key: MYSQL_USER 
        - name: MYSQL_PASSWORD
          valueFrom: 
             secretKeyRef:
                name: mysql-credentials
                key: MYSQL_PASSWORD 
        - name: MYSQL_DATABASE
          value: cctv_db
        - name: MYSQL_HOST
          value: mysql
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args: ["./Entrypoint.sh"]

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cctv
  labels:
    ostraining: "lamp"
spec:
  selector:
    app: php
  ports:
  - name: http
    port: 8000       # Service port
    targetPort: 8000 # Container port
    protocol: TCP
  type: LoadBalancer


