apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cctv
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: MYSQL_DATABASE
          value: "cctv_db"
        - name: MYSQL_USER
          value: "cctv_user"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: cctv
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
