apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: cctv
  labels:
    ostraining: "lamp"
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=  # Base64 of "12345678"
  MYSQL_PASSWORD: cGFzc3dvcmQ=       # Base64 of "password"
  MYSQL_USER: Y2N0dg==               # Base64 of "cctv"
