

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cctv
  labels:
    ostraining: "lamp"
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30006  # NodePort should be in the range 30000-32767
  type: NodePort